name: qr_code_scanner
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  auto_route: 5.0.4
  cupertino_icons: 1.0.5
  easy_localization: 3.0.2-dev
  encrypt: 5.0.1
  flutter:
    sdk: flutter
  flutter_bloc: 8.1.1
  flutter_hooks: 0.18.5+1
  freezed_annotation: 2.2.0
  hive: 2.2.3
  hive_flutter: 1.1.0
  logger: 1.1.0
  lottie: 2.1.0
  mobile_scanner: 3.0.0-beta.4
  path_provider: 2.0.11
  shared_preferences: 2.0.15
  url_launcher: 6.1.7
  uuid: 3.0.7

dev_dependencies:
  auto_route_generator: 5.0.3
  build_runner: 2.3.3
  flutter_flavorizr: 2.1.5
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter
  freezed: 2.3.2
  hive_generator: 2.0.0
  json_serializable: 6.5.4

flutter:
  uses-material-design: true
  assets:
    - assets/app_icons/
    - assets/l10n/
    - assets/animations/
  fonts:
    - family: Titillium Web
      fonts:
        - asset: assets/fonts/titillium_web/TitilliumWeb-Regular.ttf
          weight: 400
        - asset: assets/fonts/titillium_web/TitilliumWeb-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/titillium_web/TitilliumWeb-Bold.ttf
          weight: 700
        - asset: assets/fonts/titillium_web/TitilliumWeb-Black.ttf
          weight: 900

flavorizr:
  flavors:
    prod:
      app:
        name: "Scanner"
        icon: "assets/app_icons/prod.png"

      android:
        applicationId: "com.workerbase.scanner"

      ios:
        bundleId: "com.workerbase.scanner"

    dev:
      app:
        name: "Scanner Dev"
        icon: "assets/app_icons/dev.png"

      android:
        applicationId: "com.workerbase.scannerDev"
      ios:
        bundleId: "com.workerbase.scannerDev"
